services:
    next:
        container_name: next-portfolio
        build:
            context: ./next
            dockerfile: Dockerfile
        restart: always
        networks:
            - vps-server_caddy

networks:
    vps-server_caddy:
        external: true
