/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    frame: Frame;
    post: Post;
    reseller: Reseller;
    product: Product;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    frame: FrameSelect<false> | FrameSelect<true>;
    post: PostSelect<false> | PostSelect<true>;
    reseller: ResellerSelect<false> | ResellerSelect<true>;
    product: ProductSelect<false> | ProductSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    infos: Info;
    home: Home;
    contact: Contact;
  };
  globalsSelect: {
    infos: InfosSelect<false> | InfosSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frame".
 */
export interface Frame {
  id: string;
  name?: string | null;
  description?: string | null;
  wheelSize?: ('26"' | '27.5"' | '29"' | '700') | null;
  sortPriority?: number | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post".
 */
export interface Post {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseller".
 */
export interface Reseller {
  id: string;
  name?: string | null;
  address?: string | null;
  city?: string | null;
  postalCode?: string | null;
  country?:
    | (
        | 'Afghanistan'
        | 'Afrique du Sud'
        | 'Albanie'
        | 'Algérie'
        | 'Allemagne'
        | 'Andorre'
        | 'Angola'
        | 'Anguilla'
        | 'Antarctique'
        | 'Antigua-et-Barbuda'
        | 'Antilles néerlandaises'
        | 'Arabie saoudite'
        | 'Argentine'
        | 'Arménie'
        | 'Aruba'
        | 'Australie'
        | 'Autriche'
        | 'Azerbaïdjan'
        | 'Bahamas'
        | 'Bahreïn'
        | 'Bangladesh'
        | 'Barbade'
        | 'Bélarus'
        | 'Belgique'
        | 'Belize'
        | 'Bénin'
        | 'Bermudes'
        | 'Bhoutan'
        | 'Bolivie'
        | 'Bosnie-Herzégovine'
        | 'Botswana'
        | 'Brésil'
        | 'Brunéi Darussalam'
        | 'Bulgarie'
        | 'Burkina Faso'
        | 'Burundi'
        | 'Cambodge'
        | 'Cameroun'
        | 'Canada'
        | 'Cap-Vert'
        | 'Ceuta et Melilla'
        | 'Chili'
        | 'Chine'
        | 'Chypre'
        | 'Colombie'
        | 'Comores'
        | 'Congo-Brazzaville'
        | 'Corée du Nord'
        | 'Corée du Sud'
        | 'Costa Rica'
        | 'Côte d’Ivoire'
        | 'Croatie'
        | 'Cuba'
        | 'Danemark'
        | 'Diego Garcia'
        | 'Djibouti'
        | 'Dominique'
        | 'Égypte'
        | 'El Salvador'
        | 'Émirats arabes unis'
        | 'Équateur'
        | 'Érythrée'
        | 'Espagne'
        | 'Estonie'
        | 'État de la Cité du Vatican'
        | 'États fédérés de Micronésie'
        | 'États-Unis'
        | 'Éthiopie'
        | 'Fidji'
        | 'Finlande'
        | 'France'
        | 'Gabon'
        | 'Gambie'
        | 'Géorgie'
        | 'Géorgie du Sud et les îles Sandwich du Sud'
        | 'Ghana'
        | 'Gibraltar'
        | 'Grèce'
        | 'Grenade'
        | 'Groenland'
        | 'Guadeloupe'
        | 'Guam'
        | 'Guatemala'
        | 'Guernesey'
        | 'Guinée'
        | 'Guinée équatoriale'
        | 'Guinée-Bissau'
        | 'Guyana'
        | 'Guyane française'
        | 'Haïti'
        | 'Honduras'
        | 'Hongrie'
        | 'Île Bouvet'
        | 'Île Christmas'
        | 'Île Clipperton'
        | "Île de l'Ascension"
        | 'Île de Man'
        | 'Île Norfolk'
        | 'Îles Åland'
        | 'Îles Caïmans'
        | 'Îles Canaries'
        | 'Îles Cocos - Keeling'
        | 'Îles Cook'
        | 'Îles Féroé'
        | 'Îles Heard et MacDonald'
        | 'Îles Malouines'
        | 'Îles Mariannes du Nord'
        | 'Îles Marshall'
        | 'Îles Mineures Éloignées des États-Unis'
        | 'Îles Salomon'
        | 'Îles Turks et Caïques'
        | 'Îles Vierges britanniques'
        | 'Îles Vierges des États-Unis'
        | 'Inde'
        | 'Indonésie'
        | 'Irak'
        | 'Iran'
        | 'Irlande'
        | 'Islande'
        | 'Israël'
        | 'Italie'
        | 'Jamaïque'
        | 'Japon'
        | 'Jersey'
        | 'Jordanie'
        | 'Kazakhstan'
        | 'Kenya'
        | 'Kirghizistan'
        | 'Kiribati'
        | 'Koweït'
        | 'Laos'
        | 'Lesotho'
        | 'Lettonie'
        | 'Liban'
        | 'Libéria'
        | 'Libye'
        | 'Liechtenstein'
        | 'Lituanie'
        | 'Luxembourg'
        | 'Macédoine'
        | 'Madagascar'
        | 'Malaisie'
        | 'Malawi'
        | 'Maldives'
        | 'Mali'
        | 'Malte'
        | 'Maroc'
        | 'Martinique'
        | 'Maurice'
        | 'Mauritanie'
        | 'Mayotte'
        | 'Mexique'
        | 'Moldavie'
        | 'Monaco'
        | 'Mongolie'
        | 'Monténégro'
        | 'Montserrat'
        | 'Mozambique'
        | 'Myanmar'
        | 'Namibie'
        | 'Nauru'
        | 'Népal'
        | 'Nicaragua'
        | 'Niger'
        | 'Nigéria'
        | 'Niue'
        | 'Norvège'
        | 'Nouvelle-Calédonie'
        | 'Nouvelle-Zélande'
        | 'Oman'
        | 'Ouganda'
        | 'Ouzbékistan'
        | 'Pakistan'
        | 'Palaos'
        | 'Panama'
        | 'Papouasie-Nouvelle-Guinée'
        | 'Paraguay'
        | 'Pays-Bas'
        | 'Pérou'
        | 'Philippines'
        | 'Pitcairn'
        | 'Pologne'
        | 'Polynésie française'
        | 'Porto Rico'
        | 'Portugal'
        | 'Qatar'
        | 'R.A.S. chinoise de Hong Kong'
        | 'R.A.S. chinoise de Macao'
        | 'régions éloignées de l’Océanie'
        | 'République centrafricaine'
        | 'République démocratique du Congo'
        | 'République dominicaine'
        | 'République tchèque'
        | 'Réunion'
        | 'Roumanie'
        | 'Royaume-Uni'
        | 'Russie'
        | 'Rwanda'
        | 'Sahara occidental'
        | 'Saint-Barthélémy'
        | 'Saint-Kitts-et-Nevis'
        | 'Saint-Marin'
        | 'Saint-Martin'
        | 'Saint-Pierre-et-Miquelon'
        | 'Saint-Vincent-et-les Grenadines'
        | 'Sainte-Hélène'
        | 'Sainte-Lucie'
        | 'Samoa'
        | 'Samoa américaines'
        | 'Sao Tomé-et-Principe'
        | 'Sénégal'
        | 'Serbie'
        | 'Serbie-et-Monténégro'
        | 'Seychelles'
        | 'Sierra Leone'
        | 'Singapour'
        | 'Slovaquie'
        | 'Slovénie'
        | 'Somalie'
        | 'Soudan'
        | 'Sri Lanka'
        | 'Suède'
        | 'Suisse'
        | 'Suriname'
        | 'Svalbard et Île Jan Mayen'
        | 'Swaziland'
        | 'Syrie'
        | 'Tadjikistan'
        | 'Taïwan'
        | 'Tanzanie'
        | 'Tchad'
        | 'Terres australes françaises'
        | "Territoire britannique de l'océan Indien"
        | 'Territoire palestinien'
        | 'Thaïlande'
        | 'Timor oriental'
        | 'Togo'
        | 'Tokelau'
        | 'Tonga'
        | 'Trinité-et-Tobago'
        | 'Tristan da Cunha'
        | 'Tunisie'
        | 'Turkménistan'
        | 'Turquie'
        | 'Tuvalu'
        | 'Ukraine'
        | 'Union européenne'
        | 'Uruguay'
        | 'Vanuatu'
        | 'Venezuela'
        | 'Viêt Nam'
        | 'Wallis-et-Futuna'
        | 'Yémen'
        | 'Zambie'
        | 'Zimbabwe'
      )
    | null;
  phone?: string | null;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: string;
  name?: string | null;
  description?: string | null;
  type?: ('frame' | 'accessory') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (string | Media)[] | null;
  price?: number | null;
  stock?: ('in-stock' | 'out-of-stock' | 'coming-soon') | null;
  models?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'frame';
        value: string | Frame;
      } | null)
    | ({
        relationTo: 'post';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'reseller';
        value: string | Reseller;
      } | null)
    | ({
        relationTo: 'product';
        value: string | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frame_select".
 */
export interface FrameSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  wheelSize?: T;
  sortPriority?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post_select".
 */
export interface PostSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseller_select".
 */
export interface ResellerSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_select".
 */
export interface ProductSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  content?: T;
  gallery?: T;
  price?: T;
  stock?: T;
  models?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infos".
 */
export interface Info {
  id: string;
  logo?: (string | null) | Media;
  instagramLink?: string | null;
  facebookLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  heroImage?: (string | null) | Media;
  heroTitle: string;
  heroDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infos_select".
 */
export interface InfosSelect<T extends boolean = true> {
  logo?: T;
  instagramLink?: T;
  facebookLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  description?: T;
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}